# Generated by Django 3.1.1 on 2020-09-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='year_month',
        ),
    ]
