# Generated by Django 3.1.1 on 2020-09-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200925_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='year_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
