# Generated by Django 3.1.1 on 2020-09-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
