# Generated by Django 3.1.1 on 2020-09-14 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200914_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='base.Item'),
        ),
    ]
